# Upstream: https://github.com/LingDong-/shan-shui-inf
NAME=ShanShui
TITLE="Shan Shui"
CLASS=ShanShuiView
BUNDLE_ID=io.kylekovary.ShanShui
BG=FFFFFF
COPYRIGHT="Art: shan-shui-inf (c) 2018 Lingdong Huang, MIT."
