#!/bin/bash
# Bundle the paint worker: shim + upstream main.js (verbatim) + our worker code,
# embedded as a string so gallery.js can start it from a Blob URL.
set -euo pipefail
cd "$(dirname "$0")"
python3 - <<'PY'
import json
parts = ["src/worker-shim.js", "Resources/main.js", "src/paint-worker.js"]
src = "\n;\n".join(open(p).read() for p in parts)
open("Resources/worker.src.js", "w").write(
    "// Generated by prebuild.sh from " + ", ".join(parts) + ". Do not edit.\n"
    "self.NF_WORKER_SRC = " + json.dumps(src) + ";\n")
PY
