# Upstream: https://github.com/LingDong-/nonflowers
NAME=Nonflowers
TITLE="Nonflowers"
CLASS=NonflowersView
BUNDLE_ID=io.kylekovary.Nonflowers
BG=FFFDE6
CYCLE=0
INDEX=gallery.html
COPYRIGHT="Art: nonflowers (c) 2018 Lingdong Huang, MIT."
