#!/bin/bash
# Bundle the fish worker: upstream fishdraw.js (verbatim) + our worker code,
# embedded as a string so plotter.js can start it from a Blob URL.
set -euo pipefail
cd "$(dirname "$0")"
python3 - <<'PY'
import json
parts = ["Resources/fishdraw.js", "src/fish-worker.js"]
src = "\n;\n".join(open(p).read() for p in parts)
open("Resources/worker.src.js", "w").write(
    "// Generated by prebuild.sh from " + ", ".join(parts) + ". Do not edit.\n"
    "self.FISH_WORKER_SRC = " + json.dumps(src) + ";\n")
PY
