# Upstream: https://github.com/LingDong-/fishdraw
NAME=FishDraw
TITLE="Fish Draw"
CLASS=FishDrawView
BUNDLE_ID=io.kylekovary.FishDraw
BG=FFFAF0
COPYRIGHT="Art: fishdraw (c) 2021 Lingdong Huang, MIT."
